name: linux

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install termscp
              run: ./.github/scripts/brew.sh
              shell: bash
