name: macos

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: macos-latest

        steps:
            - uses: actions/checkout@v2
            - name: Install termscp
              run: brew install veeso/termscp/termscp
